### ISSUE TITLE
chore/PRのチェックリストのtasksがすべて埋まらない

### ISSUE THREAD

**Issue by kenken714** [traP-jp/traO-Judge-judge#42]
現状だとすべてがチェックボックスになっていて、 5 of 7 tasks と表示されてしまう

**Comment by kenken714** [comment]
ラジオボタンは使えませんでした

**Comment by comavius** [comment]
https://github.com/orgs/community/discussions/4319

**Comment by comavius** [comment]
test
- **[x] a
- **[ ] b

**Comment by comavius** [comment]
**[x] a
**[ ] b

**Comment by comavius** [comment]
- [ ] a

**Comment by comavius** [comment]
- - [ ] a

**Comment by comavius** [comment]
`- - [ ] a`でtasklistを無効化できるらしい？

> https://github.com/orgs/community/discussions/4319
