### ISSUE TITLE
ファイルを管理する構造体を作る

### ISSUE THREAD

**Issue by comavius** [traP-jp/traO-Judge-judge#7]
各種ファイルのread/writeとシンボリックリンクによる依存関係を管理する構造体を作りたい
newでファイルを作成し、Dropトレイトでファイルを削除するような感じで考えています。Arc<RwLock<File>>みたいな感じにして使う予定です。いい感じのライブラリがあったらそれのほうがいいかも
https://github.com/comavius/resource-caching

**Comment by comavius** [comment]
hardlinkを作る都合上、inodeに対応するクラス/インスタンスがあると嬉しい気がします。

**Comment by comavius** [comment]
@hayatroid 実装始まってますか？:eyes:(始まっていないならtraitに変更を入れたいです)

**Comment by hayatroid** [comment]
@comavius まだ始めていません 🙇🙇🙇

**Comment by hayatroid** [comment]
@comavius [traits.rs](https://github.com/traP-jp/traO-Judge-judge/blob/develop/judge-control-app/src/custom_file/traits.rs) について質問です
- `type InitArgs` がよくわかっていないです，何を入れる想定ですか
- `FileFactory` の `get_hardlink_of` は，`original` のハードリンク一覧を取得する関数かと思ったのですが，返り値は複数（`Vec` 等）ではないのですか（1 ファイルに対し 1 つのハードリンクしか作れないみたいな制約があったりしますか）

**Comment by hayatroid** [comment]
下の質問についてはシンボリックリンクの話と混同していました　create の意で合っていますか

**Comment by comavius** [comment]
> `type InitArgs` がよくわかっていないです，何を入れる想定ですか

`trait File`を実装する構造体を初期化するために必要な情報を入れる予定です。たとえばテキストファイルなら内容の文字列が入ると思います。

**Comment by comavius** [comment]
#35
